# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build & Release Plugin

on:
  push:
    tags:
      - 'v*'

env:
  PLUGIN_NAME: BetterEssenceCorruptionHelper
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download ExileCore dependencies
      run: |
        mkdir -p libs
        wget -q https://github.com/exApiTools/ExileApi-Compiled/raw/refs/heads/master/ExileCore.dll -O libs/ExileCore.dll
        wget -q https://github.com/exApiTools/ExileApi-Compiled/raw/refs/heads/master/GameOffsets.dll -O libs/GameOffsets.dll

    - name: Build Release DLL
      run: dotnet build ${{ env.PLUGIN_NAME }}.csproj --configuration Release

    - name: Create plugin folder
      run: |
        mkdir -p release/${{ env.PLUGIN_NAME }}
        cp bin/Release/net8.0-windows/${{ env.PLUGIN_NAME }}.dll release/${{ env.PLUGIN_NAME }}/

    - name: Zip plugin
      run: |
        cd release
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: release/${{ env.PLUGIN_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

